version: "3.7"

services:
  app:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
      - ./.setup/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    build:
      context: .
      dockerfile: .setup/Dockerfile
    volumes:
      - ./:/var/www/html
